from __future__ import annotations

from typing import Iterator, overload

class Bytes:
    """Immutable byte buffer using the Compact strategy.

    Stores <=62 bytes inline; aggressively converts heap back to inline when
    data shrinks. Optimized for memory efficiency over ``bytes::Bytes`` interop.
    """

    def __init__(self) -> None:
        """Create a new empty Bytes."""
        ...
    @staticmethod
    def from_bytes(data: bytes) -> Bytes:
        """Create by copying from a bytes-like object."""
        ...
    @staticmethod
    def from_str(s: str) -> Bytes:
        """Create from a UTF-8 string."""
        ...
    def __len__(self) -> int:
        """Return the number of readable bytes."""
        ...
    def __bool__(self) -> bool:
        """Return True if any bytes remain."""
        ...
    def __bytes__(self, /) -> bytes:
        """Return contents as a Python bytes object."""
        ...
    def __str__(self) -> str:
        """Decode contents as UTF-8."""
        ...
    def __repr__(self) -> str:
        """Return debug representation."""
        ...
    def __hash__(self) -> int:
        """Compute hash of the buffer contents."""
        ...
    def __contains__(self, item: object) -> bool:
        """Check membership of a byte value or subsequence."""
        ...
    @overload
    def __getitem__(self, index: int) -> int: ...
    @overload
    def __getitem__(self, index: slice) -> bytes: ...
    def __iter__(self) -> Iterator[int]:
        """Iterate over readable bytes, yielding int values."""
        ...
    def __eq__(self, other: object) -> bool: ...
    def __ne__(self, other: object) -> bool: ...
    def __lt__(self, other: object) -> bool: ...
    def __le__(self, other: object) -> bool: ...
    def __gt__(self, other: object) -> bool: ...
    def __ge__(self, other: object) -> bool: ...
    def __copy__(self) -> Bytes:
        """Support copy.copy()."""
        ...
    def __deepcopy__(self, memo: object) -> Bytes:
        """Support copy.deepcopy()."""
        ...
    def __reduce__(self) -> tuple[object, tuple[bytes]]:
        """Support pickling."""
        ...
    def as_bytes(self) -> bytes:
        """Return the readable data as bytes."""
        ...
    def to_string(self) -> str:
        """Decode contents as UTF-8."""
        ...
    def is_inline(self) -> bool:
        """Return True if stored inline (<=62 bytes)."""
        ...
    def is_heap(self) -> bool:
        """Return True if stored on the heap."""
        ...
    def remaining(self) -> int:
        """Return the number of bytes available for reading."""
        ...
    def advance(self, cnt: int) -> None:
        """Advance the read cursor by ``cnt`` bytes."""
        ...
    def truncate(self, new_len: int) -> None:
        """Shorten the buffer to ``new_len`` bytes."""
        ...
    def clear(self) -> None:
        """Remove all data."""
        ...
    def split_to(self, at: int) -> Bytes:
        """Split at ``at``, returning ``[0, at)``. Self becomes ``[at, len)``."""
        ...
    def split_off(self, at: int) -> Bytes:
        """Split at ``at``, returning ``[at, len)``. Self becomes ``[0, at)``."""
        ...
    def slice(self, start: int, end: int) -> Bytes:
        """Return a view of bytes in ``[start, end)``."""
        ...
    def get_u8(self) -> int:
        """Read an unsigned 8-bit integer. Advances cursor by 1."""
        ...
    def get_i8(self) -> int:
        """Read a signed 8-bit integer. Advances cursor by 1."""
        ...
    def get_u16(self) -> int:
        """Read an unsigned 16-bit integer (big-endian). Advances cursor by 2."""
        ...
    def get_u16_le(self) -> int:
        """Read an unsigned 16-bit integer (little-endian). Advances cursor by 2."""
        ...
    def get_i16(self) -> int:
        """Read a signed 16-bit integer (big-endian). Advances cursor by 2."""
        ...
    def get_i16_le(self) -> int:
        """Read a signed 16-bit integer (little-endian). Advances cursor by 2."""
        ...
    def get_u32(self) -> int:
        """Read an unsigned 32-bit integer (big-endian). Advances cursor by 4."""
        ...
    def get_u32_le(self) -> int:
        """Read an unsigned 32-bit integer (little-endian). Advances cursor by 4."""
        ...
    def get_i32(self) -> int:
        """Read a signed 32-bit integer (big-endian). Advances cursor by 4."""
        ...
    def get_i32_le(self) -> int:
        """Read a signed 32-bit integer (little-endian). Advances cursor by 4."""
        ...
    def get_f32(self) -> float:
        """Read a 32-bit float (big-endian). Advances cursor by 4."""
        ...
    def get_f32_le(self) -> float:
        """Read a 32-bit float (little-endian). Advances cursor by 4."""
        ...
    def get_u64(self) -> int:
        """Read an unsigned 64-bit integer (big-endian). Advances cursor by 8."""
        ...
    def get_u64_le(self) -> int:
        """Read an unsigned 64-bit integer (little-endian). Advances cursor by 8."""
        ...
    def get_i64(self) -> int:
        """Read a signed 64-bit integer (big-endian). Advances cursor by 8."""
        ...
    def get_i64_le(self) -> int:
        """Read a signed 64-bit integer (little-endian). Advances cursor by 8."""
        ...
    def get_f64(self) -> float:
        """Read a 64-bit float (big-endian). Advances cursor by 8."""
        ...
    def get_f64_le(self) -> float:
        """Read a 64-bit float (little-endian). Advances cursor by 8."""
        ...
    def get_u128(self) -> int:
        """Read an unsigned 128-bit integer (big-endian). Advances cursor by 16."""
        ...
    def get_u128_le(self) -> int:
        """Read an unsigned 128-bit integer (little-endian). Advances cursor by 16."""
        ...
    def get_i128(self) -> int:
        """Read a signed 128-bit integer (big-endian). Advances cursor by 16."""
        ...
    def get_i128_le(self) -> int:
        """Read a signed 128-bit integer (little-endian). Advances cursor by 16."""
        ...
    def get_uint(self, nbytes: int) -> int:
        """Read an unsigned integer of ``nbytes`` bytes (big-endian, max 8)."""
        ...
    def get_uint_le(self, nbytes: int) -> int:
        """Read an unsigned integer of ``nbytes`` bytes (little-endian, max 8)."""
        ...
    def get_int(self, nbytes: int) -> int:
        """Read a signed integer of ``nbytes`` bytes (big-endian, max 8)."""
        ...
    def get_int_le(self, nbytes: int) -> int:
        """Read a signed integer of ``nbytes`` bytes (little-endian, max 8)."""
        ...

class Utf8Bytes:
    """Immutable UTF-8 string using the Compact strategy.

    Guarantees valid UTF-8. Aggressively inlines to minimize memory.
    """

    def __init__(self) -> None:
        """Create a new empty Utf8Bytes."""
        ...
    @staticmethod
    def from_str(s: str) -> Utf8Bytes:
        """Create from a string."""
        ...
    def __len__(self) -> int:
        """Return byte length."""
        ...
    def __bool__(self) -> bool:
        """Return True if non-empty."""
        ...
    def __bytes__(self, /) -> bytes:
        """Return raw UTF-8 bytes."""
        ...
    def __str__(self) -> str:
        """Return the string contents."""
        ...
    def __repr__(self) -> str:
        """Return debug representation."""
        ...
    def __hash__(self) -> int:
        """Compute hash of the string contents."""
        ...
    def __contains__(self, item: object) -> bool:
        """Check if a substring is contained."""
        ...
    @overload
    def __getitem__(self, index: int) -> str: ...
    @overload
    def __getitem__(self, index: slice) -> str: ...
    def __iter__(self) -> Iterator[str]:
        """Iterate over characters, yielding single-char strings."""
        ...
    def __eq__(self, other: object) -> bool: ...
    def __ne__(self, other: object) -> bool: ...
    def __lt__(self, other: object) -> bool: ...
    def __le__(self, other: object) -> bool: ...
    def __gt__(self, other: object) -> bool: ...
    def __ge__(self, other: object) -> bool: ...
    def __copy__(self) -> Utf8Bytes:
        """Support copy.copy()."""
        ...
    def __deepcopy__(self, memo: object) -> Utf8Bytes:
        """Support copy.deepcopy()."""
        ...
    def __reduce__(self) -> tuple[object, tuple[str]]:
        """Support pickling."""
        ...
    def split_to(self, at: int) -> Utf8Bytes:
        """Split at byte position ``at`` (must be a char boundary)."""
        ...
    def split_off(self, at: int) -> Utf8Bytes:
        """Split at byte position ``at``, returning the tail."""
        ...
    def slice(self, start: int, end: int) -> Utf8Bytes:
        """Return a view of the substring in byte range ``[start, end)``."""
        ...
    def is_inline(self) -> bool:
        """Return True if stored inline (<=62 bytes)."""
        ...
    def is_heap(self) -> bool:
        """Return True if stored on the heap."""
        ...
    def remaining(self) -> int:
        """Return the number of bytes available for reading."""
        ...
    def advance(self, cnt: int) -> None:
        """Advance the read cursor by ``cnt`` bytes."""
        ...
    def get_u8(self) -> int:
        """Read an unsigned 8-bit integer. Advances cursor by 1."""
        ...
    def get_i8(self) -> int:
        """Read a signed 8-bit integer. Advances cursor by 1."""
        ...
    def get_u16(self) -> int:
        """Read an unsigned 16-bit integer (big-endian). Advances cursor by 2."""
        ...
    def get_u16_le(self) -> int:
        """Read an unsigned 16-bit integer (little-endian). Advances cursor by 2."""
        ...
    def get_i16(self) -> int:
        """Read a signed 16-bit integer (big-endian). Advances cursor by 2."""
        ...
    def get_i16_le(self) -> int:
        """Read a signed 16-bit integer (little-endian). Advances cursor by 2."""
        ...
    def get_u32(self) -> int:
        """Read an unsigned 32-bit integer (big-endian). Advances cursor by 4."""
        ...
    def get_u32_le(self) -> int:
        """Read an unsigned 32-bit integer (little-endian). Advances cursor by 4."""
        ...
    def get_i32(self) -> int:
        """Read a signed 32-bit integer (big-endian). Advances cursor by 4."""
        ...
    def get_i32_le(self) -> int:
        """Read a signed 32-bit integer (little-endian). Advances cursor by 4."""
        ...
    def get_f32(self) -> float:
        """Read a 32-bit float (big-endian). Advances cursor by 4."""
        ...
    def get_f32_le(self) -> float:
        """Read a 32-bit float (little-endian). Advances cursor by 4."""
        ...
    def get_u64(self) -> int:
        """Read an unsigned 64-bit integer (big-endian). Advances cursor by 8."""
        ...
    def get_u64_le(self) -> int:
        """Read an unsigned 64-bit integer (little-endian). Advances cursor by 8."""
        ...
    def get_i64(self) -> int:
        """Read a signed 64-bit integer (big-endian). Advances cursor by 8."""
        ...
    def get_i64_le(self) -> int:
        """Read a signed 64-bit integer (little-endian). Advances cursor by 8."""
        ...
    def get_f64(self) -> float:
        """Read a 64-bit float (big-endian). Advances cursor by 8."""
        ...
    def get_f64_le(self) -> float:
        """Read a 64-bit float (little-endian). Advances cursor by 8."""
        ...
    def get_u128(self) -> int:
        """Read an unsigned 128-bit integer (big-endian). Advances cursor by 16."""
        ...
    def get_u128_le(self) -> int:
        """Read an unsigned 128-bit integer (little-endian). Advances cursor by 16."""
        ...
    def get_i128(self) -> int:
        """Read a signed 128-bit integer (big-endian). Advances cursor by 16."""
        ...
    def get_i128_le(self) -> int:
        """Read a signed 128-bit integer (little-endian). Advances cursor by 16."""
        ...
    def get_uint(self, nbytes: int) -> int:
        """Read an unsigned integer of ``nbytes`` bytes (big-endian, max 8)."""
        ...
    def get_uint_le(self, nbytes: int) -> int:
        """Read an unsigned integer of ``nbytes`` bytes (little-endian, max 8)."""
        ...
    def get_int(self, nbytes: int) -> int:
        """Read a signed integer of ``nbytes`` bytes (big-endian, max 8)."""
        ...
    def get_int_le(self, nbytes: int) -> int:
        """Read a signed integer of ``nbytes`` bytes (little-endian, max 8)."""
        ...
