from __future__ import annotations

from typing import ClassVar, Iterator, overload

class Buffer:
    """Fixed-size inline byte buffer (max 62 bytes).

    Stores up to 62 bytes on the stack with no heap allocation.
    All read/write operations panic or raise on overflow.
    """

    def __init__(self) -> None:
        """Create a new empty Buffer."""
        ...
    @staticmethod
    def from_bytes(data: bytes) -> Buffer:
        """Create a Buffer by copying from a bytes-like object.

        Raises:
            BufferError: If data exceeds 62 bytes.
        """
        ...
    @staticmethod
    def from_str(s: str) -> Buffer:
        """Create a Buffer from a UTF-8 string.

        Raises:
            BufferError: If the encoded string exceeds 62 bytes.
        """
        ...
    def __len__(self) -> int:
        """Return the number of readable bytes."""
        ...
    def __bool__(self) -> bool:
        """Return True if any bytes remain."""
        ...
    def __bytes__(self, /) -> bytes:
        """Return contents as a Python bytes object."""
        ...
    def __str__(self) -> str:
        """Decode contents as UTF-8.

        Raises:
            UnicodeDecodeError: If contents are not valid UTF-8.
        """
        ...
    def __repr__(self) -> str:
        """Return debug representation."""
        ...
    __hash__: ClassVar[None]
    def __contains__(self, item: object) -> bool:
        """Check membership of a byte value or subsequence."""
        ...
    @overload
    def __getitem__(self, index: int) -> int: ...
    @overload
    def __getitem__(self, index: slice) -> bytes: ...
    def __setitem__(self, index: int | slice, value: int | bytes) -> None:
        """Assign to a single byte position or slice."""
        ...
    def __iter__(self) -> Iterator[int]:
        """Iterate over readable bytes, yielding int values."""
        ...
    def __eq__(self, other: object) -> bool: ...
    def __ne__(self, other: object) -> bool: ...
    def __lt__(self, other: object) -> bool: ...
    def __le__(self, other: object) -> bool: ...
    def __gt__(self, other: object) -> bool: ...
    def __ge__(self, other: object) -> bool: ...
    def __reduce__(self) -> tuple[object, tuple[bytes]]:
        """Support pickling via pickle.dumps / pickle.loads."""
        ...
    def as_bytes(self) -> bytes:
        """Return the readable data as a Python bytes object."""
        ...
    def to_string(self) -> str:
        """Decode the buffer contents as UTF-8."""
        ...
    def get_u8(self) -> int:
        """Read an unsigned 8-bit integer. Advances cursor by 1."""
        ...
    def get_i8(self) -> int:
        """Read a signed 8-bit integer. Advances cursor by 1."""
        ...
    def get_u16(self) -> int:
        """Read an unsigned 16-bit integer (big-endian). Advances cursor by 2."""
        ...
    def get_u16_le(self) -> int:
        """Read an unsigned 16-bit integer (little-endian). Advances cursor by 2."""
        ...
    def get_i16(self) -> int:
        """Read a signed 16-bit integer (big-endian). Advances cursor by 2."""
        ...
    def get_i16_le(self) -> int:
        """Read a signed 16-bit integer (little-endian). Advances cursor by 2."""
        ...
    def get_u32(self) -> int:
        """Read an unsigned 32-bit integer (big-endian). Advances cursor by 4."""
        ...
    def get_u32_le(self) -> int:
        """Read an unsigned 32-bit integer (little-endian). Advances cursor by 4."""
        ...
    def get_i32(self) -> int:
        """Read a signed 32-bit integer (big-endian). Advances cursor by 4."""
        ...
    def get_i32_le(self) -> int:
        """Read a signed 32-bit integer (little-endian). Advances cursor by 4."""
        ...
    def get_f32(self) -> float:
        """Read a 32-bit float (big-endian). Advances cursor by 4."""
        ...
    def get_f32_le(self) -> float:
        """Read a 32-bit float (little-endian). Advances cursor by 4."""
        ...
    def get_u64(self) -> int:
        """Read an unsigned 64-bit integer (big-endian). Advances cursor by 8."""
        ...
    def get_u64_le(self) -> int:
        """Read an unsigned 64-bit integer (little-endian). Advances cursor by 8."""
        ...
    def get_i64(self) -> int:
        """Read a signed 64-bit integer (big-endian). Advances cursor by 8."""
        ...
    def get_i64_le(self) -> int:
        """Read a signed 64-bit integer (little-endian). Advances cursor by 8."""
        ...
    def get_f64(self) -> float:
        """Read a 64-bit float (big-endian). Advances cursor by 8."""
        ...
    def get_f64_le(self) -> float:
        """Read a 64-bit float (little-endian). Advances cursor by 8."""
        ...
    def get_u128(self) -> int:
        """Read an unsigned 128-bit integer (big-endian). Advances cursor by 16."""
        ...
    def get_u128_le(self) -> int:
        """Read an unsigned 128-bit integer (little-endian). Advances cursor by 16."""
        ...
    def get_i128(self) -> int:
        """Read a signed 128-bit integer (big-endian). Advances cursor by 16."""
        ...
    def get_i128_le(self) -> int:
        """Read a signed 128-bit integer (little-endian). Advances cursor by 16."""
        ...
    def get_uint(self, nbytes: int) -> int:
        """Read an unsigned integer of ``nbytes`` bytes (big-endian, 0 through 8)."""
        ...
    def get_uint_le(self, nbytes: int) -> int:
        """Read an unsigned integer of ``nbytes`` bytes (little-endian, 0 through 8)."""
        ...
    def get_int(self, nbytes: int) -> int:
        """Read a signed integer of ``nbytes`` bytes (big-endian, 0 through 8)."""
        ...
    def get_int_le(self, nbytes: int) -> int:
        """Read a signed integer of ``nbytes`` bytes (little-endian, 0 through 8)."""
        ...
    def remaining(self) -> int:
        """Return the number of bytes available for reading."""
        ...
    def remaining_mut(self) -> int:
        """Return the number of bytes available for writing."""
        ...
    def advance(self, cnt: int) -> None:
        """Advance the read cursor by ``cnt`` bytes."""
        ...
    def put_slice(self, data: bytes) -> None:
        """Write a byte slice to the buffer."""
        ...
    def put_bytes(self, val: int, cnt: int) -> None:
        """Write byte ``val`` repeated ``cnt`` times."""
        ...
    def put_u8(self, val: int) -> None:
        """Write an unsigned 8-bit integer."""
        ...
    def put_i8(self, val: int) -> None:
        """Write a signed 8-bit integer."""
        ...
    def put_u16(self, val: int) -> None:
        """Write an unsigned 16-bit integer (big-endian)."""
        ...
    def put_u16_le(self, val: int) -> None:
        """Write an unsigned 16-bit integer (little-endian)."""
        ...
    def put_i16(self, val: int) -> None:
        """Write a signed 16-bit integer (big-endian)."""
        ...
    def put_i16_le(self, val: int) -> None:
        """Write a signed 16-bit integer (little-endian)."""
        ...
    def put_u32(self, val: int) -> None:
        """Write an unsigned 32-bit integer (big-endian)."""
        ...
    def put_u32_le(self, val: int) -> None:
        """Write an unsigned 32-bit integer (little-endian)."""
        ...
    def put_i32(self, val: int) -> None:
        """Write a signed 32-bit integer (big-endian)."""
        ...
    def put_i32_le(self, val: int) -> None:
        """Write a signed 32-bit integer (little-endian)."""
        ...
    def put_f32(self, val: float) -> None:
        """Write a 32-bit float (big-endian)."""
        ...
    def put_f32_le(self, val: float) -> None:
        """Write a 32-bit float (little-endian)."""
        ...
    def put_u64(self, val: int) -> None:
        """Write an unsigned 64-bit integer (big-endian)."""
        ...
    def put_u64_le(self, val: int) -> None:
        """Write an unsigned 64-bit integer (little-endian)."""
        ...
    def put_i64(self, val: int) -> None:
        """Write a signed 64-bit integer (big-endian)."""
        ...
    def put_i64_le(self, val: int) -> None:
        """Write a signed 64-bit integer (little-endian)."""
        ...
    def put_f64(self, val: float) -> None:
        """Write a 64-bit float (big-endian)."""
        ...
    def put_f64_le(self, val: float) -> None:
        """Write a 64-bit float (little-endian)."""
        ...
    def put_u128(self, val: int) -> None:
        """Write an unsigned 128-bit integer (big-endian)."""
        ...
    def put_u128_le(self, val: int) -> None:
        """Write an unsigned 128-bit integer (little-endian)."""
        ...
    def put_i128(self, val: int) -> None:
        """Write a signed 128-bit integer (big-endian)."""
        ...
    def put_i128_le(self, val: int) -> None:
        """Write a signed 128-bit integer (little-endian)."""
        ...
    def put_uint(self, val: int, nbytes: int) -> None:
        """Write an unsigned integer as ``nbytes`` bytes (big-endian, 0 through 8)."""
        ...
    def put_uint_le(self, val: int, nbytes: int) -> None:
        """Write an unsigned integer as ``nbytes`` bytes (little-endian, 0 through 8)."""
        ...
    def put_int(self, val: int, nbytes: int) -> None:
        """Write a signed integer as ``nbytes`` bytes (big-endian, 0 through 8)."""
        ...
    def put_int_le(self, val: int, nbytes: int) -> None:
        """Write a signed integer as ``nbytes`` bytes (little-endian, 0 through 8)."""
        ...
    def clear(self) -> None:
        """Remove all data, preserving capacity."""
        ...
    def truncate(self, new_len: int) -> None:
        """Shorten the buffer to ``new_len`` bytes."""
        ...
    def capacity(self) -> int:
        """Return the writable capacity in bytes."""
        ...
    def resize(self, new_len: int) -> None:
        """Resize the buffer to ``new_len``, zero-filling if grown."""
        ...
    def split_to(self, at: int) -> Buffer:
        """Split at ``at``, returning ``[0, at)``. Self becomes ``[at, len)``."""
        ...
    def split_off(self, at: int) -> Buffer:
        """Split at ``at``, returning ``[at, len)``. Self becomes ``[0, at)``."""
        ...
    def slice(self, start: int, end: int) -> Buffer:
        """Return a copy of bytes in ``[start, end)``."""
        ...

class BytesMut:
    """Growable mutable byte buffer with inline (<=62 bytes) / heap storage."""

    def __init__(self) -> None:
        """Create a new empty BytesMut."""
        ...
    @staticmethod
    def with_capacity(capacity: int) -> BytesMut:
        """Create a BytesMut with pre-allocated capacity."""
        ...
    @staticmethod
    def zeroed(len: int) -> BytesMut:
        """Create a BytesMut of ``len`` zero bytes."""
        ...
    @staticmethod
    def from_bytes(data: bytes) -> BytesMut:
        """Create a BytesMut by copying from bytes."""
        ...
    @staticmethod
    def from_str(s: str) -> BytesMut:
        """Create a BytesMut from a UTF-8 string."""
        ...
    def __len__(self) -> int:
        """Return the number of readable bytes."""
        ...
    def __bool__(self) -> bool:
        """Return True if any bytes remain."""
        ...
    def __bytes__(self, /) -> bytes:
        """Return contents as a Python bytes object."""
        ...
    def __str__(self) -> str:
        """Decode contents as UTF-8."""
        ...
    def __repr__(self) -> str:
        """Return debug representation."""
        ...
    __hash__: ClassVar[None]
    def __contains__(self, item: object) -> bool:
        """Check membership of a byte value or subsequence."""
        ...
    @overload
    def __getitem__(self, index: int) -> int: ...
    @overload
    def __getitem__(self, index: slice) -> bytes: ...
    def __setitem__(self, index: int | slice, value: int | bytes) -> None:
        """Assign to a single byte position or slice."""
        ...
    def __iter__(self) -> Iterator[int]:
        """Iterate over readable bytes, yielding int values."""
        ...
    def __eq__(self, other: object) -> bool: ...
    def __ne__(self, other: object) -> bool: ...
    def __lt__(self, other: object) -> bool: ...
    def __le__(self, other: object) -> bool: ...
    def __gt__(self, other: object) -> bool: ...
    def __ge__(self, other: object) -> bool: ...
    def __copy__(self) -> BytesMut:
        """Support copy.copy()."""
        ...
    def __deepcopy__(self, memo: object) -> BytesMut:
        """Support copy.deepcopy()."""
        ...
    def __reduce__(self) -> tuple[object, tuple[bytes]]:
        """Support pickling."""
        ...
    def as_bytes(self) -> bytes:
        """Return the readable data as bytes."""
        ...
    def to_string(self) -> str:
        """Decode contents as UTF-8."""
        ...
    def is_inline(self) -> bool:
        """Return True if stored inline (<=62 bytes)."""
        ...
    def is_heap(self) -> bool:
        """Return True if stored on the heap."""
        ...
    def len(self) -> int:
        """Return the byte length."""
        ...
    def capacity(self) -> int:
        """Return the total capacity."""
        ...
    def remaining(self) -> int:
        """Return the number of bytes available for reading."""
        ...
    def remaining_mut(self) -> int:
        """Return the number of bytes available for writing."""
        ...
    def advance(self, cnt: int) -> None:
        """Advance the read cursor by ``cnt`` bytes."""
        ...
    def get_u8(self) -> int:
        """Read an unsigned 8-bit integer. Advances cursor by 1."""
        ...
    def get_i8(self) -> int:
        """Read a signed 8-bit integer. Advances cursor by 1."""
        ...
    def get_u16(self) -> int:
        """Read an unsigned 16-bit integer (big-endian). Advances cursor by 2."""
        ...
    def get_u16_le(self) -> int:
        """Read an unsigned 16-bit integer (little-endian). Advances cursor by 2."""
        ...
    def get_i16(self) -> int:
        """Read a signed 16-bit integer (big-endian). Advances cursor by 2."""
        ...
    def get_i16_le(self) -> int:
        """Read a signed 16-bit integer (little-endian). Advances cursor by 2."""
        ...
    def get_u32(self) -> int:
        """Read an unsigned 32-bit integer (big-endian). Advances cursor by 4."""
        ...
    def get_u32_le(self) -> int:
        """Read an unsigned 32-bit integer (little-endian). Advances cursor by 4."""
        ...
    def get_i32(self) -> int:
        """Read a signed 32-bit integer (big-endian). Advances cursor by 4."""
        ...
    def get_i32_le(self) -> int:
        """Read a signed 32-bit integer (little-endian). Advances cursor by 4."""
        ...
    def get_f32(self) -> float:
        """Read a 32-bit float (big-endian). Advances cursor by 4."""
        ...
    def get_f32_le(self) -> float:
        """Read a 32-bit float (little-endian). Advances cursor by 4."""
        ...
    def get_u64(self) -> int:
        """Read an unsigned 64-bit integer (big-endian). Advances cursor by 8."""
        ...
    def get_u64_le(self) -> int:
        """Read an unsigned 64-bit integer (little-endian). Advances cursor by 8."""
        ...
    def get_i64(self) -> int:
        """Read a signed 64-bit integer (big-endian). Advances cursor by 8."""
        ...
    def get_i64_le(self) -> int:
        """Read a signed 64-bit integer (little-endian). Advances cursor by 8."""
        ...
    def get_f64(self) -> float:
        """Read a 64-bit float (big-endian). Advances cursor by 8."""
        ...
    def get_f64_le(self) -> float:
        """Read a 64-bit float (little-endian). Advances cursor by 8."""
        ...
    def get_u128(self) -> int:
        """Read an unsigned 128-bit integer (big-endian). Advances cursor by 16."""
        ...
    def get_u128_le(self) -> int:
        """Read an unsigned 128-bit integer (little-endian). Advances cursor by 16."""
        ...
    def get_i128(self) -> int:
        """Read a signed 128-bit integer (big-endian). Advances cursor by 16."""
        ...
    def get_i128_le(self) -> int:
        """Read a signed 128-bit integer (little-endian). Advances cursor by 16."""
        ...
    def get_uint(self, nbytes: int) -> int:
        """Read an unsigned integer of ``nbytes`` bytes (big-endian, 0 through 8)."""
        ...
    def get_uint_le(self, nbytes: int) -> int:
        """Read an unsigned integer of ``nbytes`` bytes (little-endian, 0 through 8)."""
        ...
    def get_int(self, nbytes: int) -> int:
        """Read a signed integer of ``nbytes`` bytes (big-endian, 0 through 8)."""
        ...
    def get_int_le(self, nbytes: int) -> int:
        """Read a signed integer of ``nbytes`` bytes (little-endian, 0 through 8)."""
        ...
    def clear(self) -> None:
        """Remove all data, preserving capacity."""
        ...
    def truncate(self, new_len: int) -> None:
        """Shorten the buffer to ``new_len`` bytes."""
        ...
    def reserve(self, additional: int) -> None:
        """Reserve capacity for at least ``additional`` more bytes."""
        ...
    def put_slice(self, data: bytes) -> None:
        """Write a byte slice to the buffer."""
        ...
    def put_bytes(self, val: int, cnt: int) -> None:
        """Write byte ``val`` repeated ``cnt`` times."""
        ...
    def put_u8(self, val: int) -> None:
        """Write an unsigned 8-bit integer."""
        ...
    def put_i8(self, val: int) -> None:
        """Write a signed 8-bit integer."""
        ...
    def put_u16(self, val: int) -> None:
        """Write an unsigned 16-bit integer (big-endian)."""
        ...
    def put_u16_le(self, val: int) -> None:
        """Write an unsigned 16-bit integer (little-endian)."""
        ...
    def put_i16(self, val: int) -> None:
        """Write a signed 16-bit integer (big-endian)."""
        ...
    def put_i16_le(self, val: int) -> None:
        """Write a signed 16-bit integer (little-endian)."""
        ...
    def put_u32(self, val: int) -> None:
        """Write an unsigned 32-bit integer (big-endian)."""
        ...
    def put_u32_le(self, val: int) -> None:
        """Write an unsigned 32-bit integer (little-endian)."""
        ...
    def put_i32(self, val: int) -> None:
        """Write a signed 32-bit integer (big-endian)."""
        ...
    def put_i32_le(self, val: int) -> None:
        """Write a signed 32-bit integer (little-endian)."""
        ...
    def put_f32(self, val: float) -> None:
        """Write a 32-bit float (big-endian)."""
        ...
    def put_f32_le(self, val: float) -> None:
        """Write a 32-bit float (little-endian)."""
        ...
    def put_u64(self, val: int) -> None:
        """Write an unsigned 64-bit integer (big-endian)."""
        ...
    def put_u64_le(self, val: int) -> None:
        """Write an unsigned 64-bit integer (little-endian)."""
        ...
    def put_i64(self, val: int) -> None:
        """Write a signed 64-bit integer (big-endian)."""
        ...
    def put_i64_le(self, val: int) -> None:
        """Write a signed 64-bit integer (little-endian)."""
        ...
    def put_f64(self, val: float) -> None:
        """Write a 64-bit float (big-endian)."""
        ...
    def put_f64_le(self, val: float) -> None:
        """Write a 64-bit float (little-endian)."""
        ...
    def put_u128(self, val: int) -> None:
        """Write an unsigned 128-bit integer (big-endian)."""
        ...
    def put_u128_le(self, val: int) -> None:
        """Write an unsigned 128-bit integer (little-endian)."""
        ...
    def put_i128(self, val: int) -> None:
        """Write a signed 128-bit integer (big-endian)."""
        ...
    def put_i128_le(self, val: int) -> None:
        """Write a signed 128-bit integer (little-endian)."""
        ...
    def put_uint(self, val: int, nbytes: int) -> None:
        """Write an unsigned integer as ``nbytes`` bytes (big-endian, 0 through 8)."""
        ...
    def put_uint_le(self, val: int, nbytes: int) -> None:
        """Write an unsigned integer as ``nbytes`` bytes (little-endian, 0 through 8)."""
        ...
    def put_int(self, val: int, nbytes: int) -> None:
        """Write a signed integer as ``nbytes`` bytes (big-endian, 0 through 8)."""
        ...
    def put_int_le(self, val: int, nbytes: int) -> None:
        """Write a signed integer as ``nbytes`` bytes (little-endian, 0 through 8)."""
        ...
    def resize(self, new_len: int, value: int) -> None:
        """Resize the buffer, filling new bytes with ``value``."""
        ...
    def split_to(self, at: int) -> BytesMut:
        """Split at ``at``, returning ``[0, at)``. Self becomes ``[at, len)``."""
        ...
    def split_off(self, at: int) -> BytesMut:
        """Split at ``at``, returning ``[at, len)``. Self becomes ``[0, at)``."""
        ...
    def split(self) -> BytesMut:
        """Remove and return all bytes. Self becomes empty."""
        ...
    def unsplit(self, other: BytesMut) -> BytesMut | None:
        """Merge ``other`` back. Returns ``other`` if merge failed (both must be heap)."""
        ...
    def make_heap(self) -> None:
        """Force promotion from inline to heap storage."""
        ...

class Utf8Buffer:
    """Fixed-size inline UTF-8 string buffer (max 62 bytes).

    Guarantees valid UTF-8. Split/slice operations check char boundaries.
    """

    def __init__(self) -> None:
        """Create a new empty Utf8Buffer."""
        ...
    @staticmethod
    def from_str(s: str) -> Utf8Buffer:
        """Create from a string. Raises if encoded bytes exceed 62."""
        ...
    def __len__(self) -> int:
        """Return the number of Unicode scalar values."""
        ...
    def __bool__(self) -> bool:
        """Return True if non-empty."""
        ...
    def __bytes__(self, /) -> bytes:
        """Return raw UTF-8 bytes."""
        ...
    def __str__(self) -> str:
        """Return the string contents."""
        ...
    def __repr__(self) -> str:
        """Return debug representation."""
        ...
    __hash__: ClassVar[None]
    def __contains__(self, item: object) -> bool:
        """Check if a substring is contained."""
        ...
    @overload
    def __getitem__(self, index: int) -> str: ...
    @overload
    def __getitem__(self, index: slice) -> str: ...
    def __iter__(self) -> Iterator[str]:
        """Iterate over characters, yielding single-char strings."""
        ...
    def __eq__(self, other: object) -> bool: ...
    def __ne__(self, other: object) -> bool: ...
    def __lt__(self, other: object) -> bool: ...
    def __le__(self, other: object) -> bool: ...
    def __gt__(self, other: object) -> bool: ...
    def __ge__(self, other: object) -> bool: ...
    def __copy__(self) -> Utf8Buffer:
        """Support copy.copy()."""
        ...
    def __deepcopy__(self, memo: object) -> Utf8Buffer:
        """Support copy.deepcopy()."""
        ...
    def __reduce__(self) -> tuple[object, tuple[str]]:
        """Support pickling."""
        ...
    def push(self, ch: str) -> None:
        """Append a single character."""
        ...
    def push_str(self, s: str) -> None:
        """Append a string."""
        ...
    def clear(self) -> None:
        """Remove all contents."""
        ...
    def truncate(self, new_len: int) -> None:
        """Shorten at a UTF-8 character boundary or raise ValueError."""
        ...
    def split_to(self, at: int) -> Utf8Buffer:
        """Split at byte position ``at`` (must be a char boundary)."""
        ...
    def split_off(self, at: int) -> Utf8Buffer:
        """Split at byte position ``at``, returning the tail."""
        ...
    def slice(self, start: int, end: int) -> Utf8Buffer:
        """Return a copy of the substring in byte range ``[start, end)``."""
        ...
    def len(self) -> int:
        """Return byte length."""
        ...
    def is_empty(self) -> bool:
        """Return True if empty."""
        ...
    def capacity(self) -> int:
        """Return writable capacity in bytes."""
        ...
    def remaining(self) -> int:
        """Return the number of bytes available for reading."""
        ...
    def advance(self, cnt: int) -> None:
        """Advance the read cursor by ``cnt`` bytes. Raises BufferError if ``cnt`` exceeds remaining bytes or does not end on a UTF-8 character boundary."""
        ...
    def get_u8(self) -> int:
        """Read an unsigned 8-bit integer. Advances cursor by 1. Raises BufferError if there are insufficient bytes or consumption ends inside a UTF-8 character."""
        ...
    def get_i8(self) -> int:
        """Read a signed 8-bit integer. Advances cursor by 1. Raises BufferError if there are insufficient bytes or consumption ends inside a UTF-8 character."""
        ...
    def get_u16(self) -> int:
        """Read an unsigned 16-bit integer (big-endian). Advances cursor by 2. Raises BufferError if there are insufficient bytes or consumption ends inside a UTF-8 character."""
        ...
    def get_u16_le(self) -> int:
        """Read an unsigned 16-bit integer (little-endian). Advances cursor by 2. Raises BufferError if there are insufficient bytes or consumption ends inside a UTF-8 character."""
        ...
    def get_i16(self) -> int:
        """Read a signed 16-bit integer (big-endian). Advances cursor by 2. Raises BufferError if there are insufficient bytes or consumption ends inside a UTF-8 character."""
        ...
    def get_i16_le(self) -> int:
        """Read a signed 16-bit integer (little-endian). Advances cursor by 2. Raises BufferError if there are insufficient bytes or consumption ends inside a UTF-8 character."""
        ...
    def get_u32(self) -> int:
        """Read an unsigned 32-bit integer (big-endian). Advances cursor by 4. Raises BufferError if there are insufficient bytes or consumption ends inside a UTF-8 character."""
        ...
    def get_u32_le(self) -> int:
        """Read an unsigned 32-bit integer (little-endian). Advances cursor by 4. Raises BufferError if there are insufficient bytes or consumption ends inside a UTF-8 character."""
        ...
    def get_i32(self) -> int:
        """Read a signed 32-bit integer (big-endian). Advances cursor by 4. Raises BufferError if there are insufficient bytes or consumption ends inside a UTF-8 character."""
        ...
    def get_i32_le(self) -> int:
        """Read a signed 32-bit integer (little-endian). Advances cursor by 4. Raises BufferError if there are insufficient bytes or consumption ends inside a UTF-8 character."""
        ...
    def get_f32(self) -> float:
        """Read a 32-bit float (big-endian). Advances cursor by 4. Raises BufferError if there are insufficient bytes or consumption ends inside a UTF-8 character."""
        ...
    def get_f32_le(self) -> float:
        """Read a 32-bit float (little-endian). Advances cursor by 4. Raises BufferError if there are insufficient bytes or consumption ends inside a UTF-8 character."""
        ...
    def get_u64(self) -> int:
        """Read an unsigned 64-bit integer (big-endian). Advances cursor by 8. Raises BufferError if there are insufficient bytes or consumption ends inside a UTF-8 character."""
        ...
    def get_u64_le(self) -> int:
        """Read an unsigned 64-bit integer (little-endian). Advances cursor by 8. Raises BufferError if there are insufficient bytes or consumption ends inside a UTF-8 character."""
        ...
    def get_i64(self) -> int:
        """Read a signed 64-bit integer (big-endian). Advances cursor by 8. Raises BufferError if there are insufficient bytes or consumption ends inside a UTF-8 character."""
        ...
    def get_i64_le(self) -> int:
        """Read a signed 64-bit integer (little-endian). Advances cursor by 8. Raises BufferError if there are insufficient bytes or consumption ends inside a UTF-8 character."""
        ...
    def get_f64(self) -> float:
        """Read a 64-bit float (big-endian). Advances cursor by 8. Raises BufferError if there are insufficient bytes or consumption ends inside a UTF-8 character."""
        ...
    def get_f64_le(self) -> float:
        """Read a 64-bit float (little-endian). Advances cursor by 8. Raises BufferError if there are insufficient bytes or consumption ends inside a UTF-8 character."""
        ...
    def get_u128(self) -> int:
        """Read an unsigned 128-bit integer (big-endian). Advances cursor by 16. Raises BufferError if there are insufficient bytes or consumption ends inside a UTF-8 character."""
        ...
    def get_u128_le(self) -> int:
        """Read an unsigned 128-bit integer (little-endian). Advances cursor by 16. Raises BufferError if there are insufficient bytes or consumption ends inside a UTF-8 character."""
        ...
    def get_i128(self) -> int:
        """Read a signed 128-bit integer (big-endian). Advances cursor by 16. Raises BufferError if there are insufficient bytes or consumption ends inside a UTF-8 character."""
        ...
    def get_i128_le(self) -> int:
        """Read a signed 128-bit integer (little-endian). Advances cursor by 16. Raises BufferError if there are insufficient bytes or consumption ends inside a UTF-8 character."""
        ...
    def get_uint(self, nbytes: int) -> int:
        """Read an unsigned integer of 0 through 8 bytes (big-endian). Raises ValueError for an invalid width and BufferError for insufficient bytes or a UTF-8 boundary."""
        ...
    def get_uint_le(self, nbytes: int) -> int:
        """Read an unsigned integer of 0 through 8 bytes (little-endian). Raises ValueError for an invalid width and BufferError for insufficient bytes or a UTF-8 boundary."""
        ...
    def get_int(self, nbytes: int) -> int:
        """Read a signed integer of 0 through 8 bytes (big-endian). Raises ValueError for an invalid width and BufferError for insufficient bytes or a UTF-8 boundary."""
        ...
    def get_int_le(self, nbytes: int) -> int:
        """Read a signed integer of 0 through 8 bytes (little-endian). Raises ValueError for an invalid width and BufferError for insufficient bytes or a UTF-8 boundary."""
        ...

class Utf8Bytes:
    """Immutable UTF-8 string with inline (<=62 bytes) / heap storage.

    Guarantees valid UTF-8. Supports zero-copy cloning via reference counting.
    """

    def __init__(self) -> None:
        """Create a new empty Utf8Bytes."""
        ...
    @staticmethod
    def from_str(s: str) -> Utf8Bytes:
        """Create from a string."""
        ...
    def __len__(self) -> int:
        """Return the number of Unicode scalar values."""
        ...
    def __bool__(self) -> bool:
        """Return True if non-empty."""
        ...
    def __bytes__(self, /) -> bytes:
        """Return raw UTF-8 bytes."""
        ...
    def __str__(self) -> str:
        """Return the string contents."""
        ...
    def __repr__(self) -> str:
        """Return debug representation."""
        ...
    __hash__: ClassVar[None]
    def __contains__(self, item: object) -> bool:
        """Check if a substring is contained."""
        ...
    @overload
    def __getitem__(self, index: int) -> str: ...
    @overload
    def __getitem__(self, index: slice) -> str: ...
    def __iter__(self) -> Iterator[str]:
        """Iterate over characters, yielding single-char strings."""
        ...
    def __eq__(self, other: object) -> bool: ...
    def __ne__(self, other: object) -> bool: ...
    def __lt__(self, other: object) -> bool: ...
    def __le__(self, other: object) -> bool: ...
    def __gt__(self, other: object) -> bool: ...
    def __ge__(self, other: object) -> bool: ...
    def __copy__(self) -> Utf8Bytes:
        """Support copy.copy()."""
        ...
    def __deepcopy__(self, memo: object) -> Utf8Bytes:
        """Support copy.deepcopy()."""
        ...
    def __reduce__(self) -> tuple[object, tuple[str]]:
        """Support pickling."""
        ...
    def split_to(self, at: int) -> Utf8Bytes:
        """Split at byte position ``at`` (must be a char boundary)."""
        ...
    def split_off(self, at: int) -> Utf8Bytes:
        """Split at byte position ``at``, returning the tail."""
        ...
    def slice(self, start: int, end: int) -> Utf8Bytes:
        """Return a view of the substring in byte range ``[start, end)``."""
        ...
    def is_inline(self) -> bool:
        """Return True if stored inline (<=62 bytes)."""
        ...
    def is_heap(self) -> bool:
        """Return True if stored on the heap."""
        ...
    def remaining(self) -> int:
        """Return the number of bytes available for reading."""
        ...
    def advance(self, cnt: int) -> None:
        """Advance the read cursor by ``cnt`` bytes. Raises BufferError if ``cnt`` exceeds remaining bytes or does not end on a UTF-8 character boundary."""
        ...
    def get_u8(self) -> int:
        """Read an unsigned 8-bit integer. Advances cursor by 1. Raises BufferError if there are insufficient bytes or consumption ends inside a UTF-8 character."""
        ...
    def get_i8(self) -> int:
        """Read a signed 8-bit integer. Advances cursor by 1. Raises BufferError if there are insufficient bytes or consumption ends inside a UTF-8 character."""
        ...
    def get_u16(self) -> int:
        """Read an unsigned 16-bit integer (big-endian). Advances cursor by 2. Raises BufferError if there are insufficient bytes or consumption ends inside a UTF-8 character."""
        ...
    def get_u16_le(self) -> int:
        """Read an unsigned 16-bit integer (little-endian). Advances cursor by 2. Raises BufferError if there are insufficient bytes or consumption ends inside a UTF-8 character."""
        ...
    def get_i16(self) -> int:
        """Read a signed 16-bit integer (big-endian). Advances cursor by 2. Raises BufferError if there are insufficient bytes or consumption ends inside a UTF-8 character."""
        ...
    def get_i16_le(self) -> int:
        """Read a signed 16-bit integer (little-endian). Advances cursor by 2. Raises BufferError if there are insufficient bytes or consumption ends inside a UTF-8 character."""
        ...
    def get_u32(self) -> int:
        """Read an unsigned 32-bit integer (big-endian). Advances cursor by 4. Raises BufferError if there are insufficient bytes or consumption ends inside a UTF-8 character."""
        ...
    def get_u32_le(self) -> int:
        """Read an unsigned 32-bit integer (little-endian). Advances cursor by 4. Raises BufferError if there are insufficient bytes or consumption ends inside a UTF-8 character."""
        ...
    def get_i32(self) -> int:
        """Read a signed 32-bit integer (big-endian). Advances cursor by 4. Raises BufferError if there are insufficient bytes or consumption ends inside a UTF-8 character."""
        ...
    def get_i32_le(self) -> int:
        """Read a signed 32-bit integer (little-endian). Advances cursor by 4. Raises BufferError if there are insufficient bytes or consumption ends inside a UTF-8 character."""
        ...
    def get_f32(self) -> float:
        """Read a 32-bit float (big-endian). Advances cursor by 4. Raises BufferError if there are insufficient bytes or consumption ends inside a UTF-8 character."""
        ...
    def get_f32_le(self) -> float:
        """Read a 32-bit float (little-endian). Advances cursor by 4. Raises BufferError if there are insufficient bytes or consumption ends inside a UTF-8 character."""
        ...
    def get_u64(self) -> int:
        """Read an unsigned 64-bit integer (big-endian). Advances cursor by 8. Raises BufferError if there are insufficient bytes or consumption ends inside a UTF-8 character."""
        ...
    def get_u64_le(self) -> int:
        """Read an unsigned 64-bit integer (little-endian). Advances cursor by 8. Raises BufferError if there are insufficient bytes or consumption ends inside a UTF-8 character."""
        ...
    def get_i64(self) -> int:
        """Read a signed 64-bit integer (big-endian). Advances cursor by 8. Raises BufferError if there are insufficient bytes or consumption ends inside a UTF-8 character."""
        ...
    def get_i64_le(self) -> int:
        """Read a signed 64-bit integer (little-endian). Advances cursor by 8. Raises BufferError if there are insufficient bytes or consumption ends inside a UTF-8 character."""
        ...
    def get_f64(self) -> float:
        """Read a 64-bit float (big-endian). Advances cursor by 8. Raises BufferError if there are insufficient bytes or consumption ends inside a UTF-8 character."""
        ...
    def get_f64_le(self) -> float:
        """Read a 64-bit float (little-endian). Advances cursor by 8. Raises BufferError if there are insufficient bytes or consumption ends inside a UTF-8 character."""
        ...
    def get_u128(self) -> int:
        """Read an unsigned 128-bit integer (big-endian). Advances cursor by 16. Raises BufferError if there are insufficient bytes or consumption ends inside a UTF-8 character."""
        ...
    def get_u128_le(self) -> int:
        """Read an unsigned 128-bit integer (little-endian). Advances cursor by 16. Raises BufferError if there are insufficient bytes or consumption ends inside a UTF-8 character."""
        ...
    def get_i128(self) -> int:
        """Read a signed 128-bit integer (big-endian). Advances cursor by 16. Raises BufferError if there are insufficient bytes or consumption ends inside a UTF-8 character."""
        ...
    def get_i128_le(self) -> int:
        """Read a signed 128-bit integer (little-endian). Advances cursor by 16. Raises BufferError if there are insufficient bytes or consumption ends inside a UTF-8 character."""
        ...
    def get_uint(self, nbytes: int) -> int:
        """Read an unsigned integer of 0 through 8 bytes (big-endian). Raises ValueError for an invalid width and BufferError for insufficient bytes or a UTF-8 boundary."""
        ...
    def get_uint_le(self, nbytes: int) -> int:
        """Read an unsigned integer of 0 through 8 bytes (little-endian). Raises ValueError for an invalid width and BufferError for insufficient bytes or a UTF-8 boundary."""
        ...
    def get_int(self, nbytes: int) -> int:
        """Read a signed integer of 0 through 8 bytes (big-endian). Raises ValueError for an invalid width and BufferError for insufficient bytes or a UTF-8 boundary."""
        ...
    def get_int_le(self, nbytes: int) -> int:
        """Read a signed integer of 0 through 8 bytes (little-endian). Raises ValueError for an invalid width and BufferError for insufficient bytes or a UTF-8 boundary."""
        ...

class Utf8BytesMut:
    """Growable mutable UTF-8 string with inline (<=62 bytes) / heap storage.

    Guarantees valid UTF-8. Split operations check char boundaries.
    """

    def __init__(self) -> None:
        """Create a new empty Utf8BytesMut."""
        ...
    @staticmethod
    def with_capacity(capacity: int) -> Utf8BytesMut:
        """Create with pre-allocated capacity."""
        ...
    @staticmethod
    def from_str(s: str) -> Utf8BytesMut:
        """Create from a string."""
        ...
    def __len__(self) -> int:
        """Return the number of Unicode scalar values."""
        ...
    def __bool__(self) -> bool:
        """Return True if non-empty."""
        ...
    def __bytes__(self, /) -> bytes:
        """Return raw UTF-8 bytes."""
        ...
    def __str__(self) -> str:
        """Return the string contents."""
        ...
    def __repr__(self) -> str:
        """Return debug representation."""
        ...
    __hash__: ClassVar[None]
    def __contains__(self, item: object) -> bool:
        """Check if a substring is contained."""
        ...
    @overload
    def __getitem__(self, index: int) -> str: ...
    @overload
    def __getitem__(self, index: slice) -> str: ...
    def __iter__(self) -> Iterator[str]:
        """Iterate over characters, yielding single-char strings."""
        ...
    def __eq__(self, other: object) -> bool: ...
    def __ne__(self, other: object) -> bool: ...
    def __lt__(self, other: object) -> bool: ...
    def __le__(self, other: object) -> bool: ...
    def __gt__(self, other: object) -> bool: ...
    def __ge__(self, other: object) -> bool: ...
    def __copy__(self) -> Utf8BytesMut:
        """Support copy.copy()."""
        ...
    def __deepcopy__(self, memo: object) -> Utf8BytesMut:
        """Support copy.deepcopy()."""
        ...
    def __reduce__(self) -> tuple[object, tuple[str]]:
        """Support pickling."""
        ...
    def push(self, ch: str) -> None:
        """Append a single character."""
        ...
    def push_str(self, s: str) -> None:
        """Append a string."""
        ...
    def clear(self) -> None:
        """Remove all contents."""
        ...
    def truncate(self, new_len: int) -> None:
        """Shorten at a UTF-8 character boundary or raise ValueError."""
        ...
    def split_to(self, at: int) -> Utf8BytesMut:
        """Split at byte position ``at`` (must be a char boundary)."""
        ...
    def split_off(self, at: int) -> Utf8BytesMut:
        """Split at byte position ``at``, returning the tail."""
        ...
    def split(self) -> Utf8BytesMut:
        """Remove and return all content. Self becomes empty."""
        ...
    def unsplit(self, other: Utf8BytesMut) -> Utf8BytesMut | None:
        """Merge ``other`` back. Returns ``other`` if merge failed."""
        ...
    def reserve(self, additional: int) -> None:
        """Reserve capacity for ``additional`` more bytes."""
        ...
    def capacity(self) -> int:
        """Return the total capacity."""
        ...
    def is_inline(self) -> bool:
        """Return True if stored inline (<=62 bytes)."""
        ...
    def is_heap(self) -> bool:
        """Return True if stored on the heap."""
        ...
    def remaining(self) -> int:
        """Return the number of bytes available for reading."""
        ...
    def advance(self, cnt: int) -> None:
        """Advance the read cursor by ``cnt`` bytes. Raises BufferError if ``cnt`` exceeds remaining bytes or does not end on a UTF-8 character boundary."""
        ...
    def get_u8(self) -> int:
        """Read an unsigned 8-bit integer. Advances cursor by 1. Raises BufferError if there are insufficient bytes or consumption ends inside a UTF-8 character."""
        ...
    def get_i8(self) -> int:
        """Read a signed 8-bit integer. Advances cursor by 1. Raises BufferError if there are insufficient bytes or consumption ends inside a UTF-8 character."""
        ...
    def get_u16(self) -> int:
        """Read an unsigned 16-bit integer (big-endian). Advances cursor by 2. Raises BufferError if there are insufficient bytes or consumption ends inside a UTF-8 character."""
        ...
    def get_u16_le(self) -> int:
        """Read an unsigned 16-bit integer (little-endian). Advances cursor by 2. Raises BufferError if there are insufficient bytes or consumption ends inside a UTF-8 character."""
        ...
    def get_i16(self) -> int:
        """Read a signed 16-bit integer (big-endian). Advances cursor by 2. Raises BufferError if there are insufficient bytes or consumption ends inside a UTF-8 character."""
        ...
    def get_i16_le(self) -> int:
        """Read a signed 16-bit integer (little-endian). Advances cursor by 2. Raises BufferError if there are insufficient bytes or consumption ends inside a UTF-8 character."""
        ...
    def get_u32(self) -> int:
        """Read an unsigned 32-bit integer (big-endian). Advances cursor by 4. Raises BufferError if there are insufficient bytes or consumption ends inside a UTF-8 character."""
        ...
    def get_u32_le(self) -> int:
        """Read an unsigned 32-bit integer (little-endian). Advances cursor by 4. Raises BufferError if there are insufficient bytes or consumption ends inside a UTF-8 character."""
        ...
    def get_i32(self) -> int:
        """Read a signed 32-bit integer (big-endian). Advances cursor by 4. Raises BufferError if there are insufficient bytes or consumption ends inside a UTF-8 character."""
        ...
    def get_i32_le(self) -> int:
        """Read a signed 32-bit integer (little-endian). Advances cursor by 4. Raises BufferError if there are insufficient bytes or consumption ends inside a UTF-8 character."""
        ...
    def get_f32(self) -> float:
        """Read a 32-bit float (big-endian). Advances cursor by 4. Raises BufferError if there are insufficient bytes or consumption ends inside a UTF-8 character."""
        ...
    def get_f32_le(self) -> float:
        """Read a 32-bit float (little-endian). Advances cursor by 4. Raises BufferError if there are insufficient bytes or consumption ends inside a UTF-8 character."""
        ...
    def get_u64(self) -> int:
        """Read an unsigned 64-bit integer (big-endian). Advances cursor by 8. Raises BufferError if there are insufficient bytes or consumption ends inside a UTF-8 character."""
        ...
    def get_u64_le(self) -> int:
        """Read an unsigned 64-bit integer (little-endian). Advances cursor by 8. Raises BufferError if there are insufficient bytes or consumption ends inside a UTF-8 character."""
        ...
    def get_i64(self) -> int:
        """Read a signed 64-bit integer (big-endian). Advances cursor by 8. Raises BufferError if there are insufficient bytes or consumption ends inside a UTF-8 character."""
        ...
    def get_i64_le(self) -> int:
        """Read a signed 64-bit integer (little-endian). Advances cursor by 8. Raises BufferError if there are insufficient bytes or consumption ends inside a UTF-8 character."""
        ...
    def get_f64(self) -> float:
        """Read a 64-bit float (big-endian). Advances cursor by 8. Raises BufferError if there are insufficient bytes or consumption ends inside a UTF-8 character."""
        ...
    def get_f64_le(self) -> float:
        """Read a 64-bit float (little-endian). Advances cursor by 8. Raises BufferError if there are insufficient bytes or consumption ends inside a UTF-8 character."""
        ...
    def get_u128(self) -> int:
        """Read an unsigned 128-bit integer (big-endian). Advances cursor by 16. Raises BufferError if there are insufficient bytes or consumption ends inside a UTF-8 character."""
        ...
    def get_u128_le(self) -> int:
        """Read an unsigned 128-bit integer (little-endian). Advances cursor by 16. Raises BufferError if there are insufficient bytes or consumption ends inside a UTF-8 character."""
        ...
    def get_i128(self) -> int:
        """Read a signed 128-bit integer (big-endian). Advances cursor by 16. Raises BufferError if there are insufficient bytes or consumption ends inside a UTF-8 character."""
        ...
    def get_i128_le(self) -> int:
        """Read a signed 128-bit integer (little-endian). Advances cursor by 16. Raises BufferError if there are insufficient bytes or consumption ends inside a UTF-8 character."""
        ...
    def get_uint(self, nbytes: int) -> int:
        """Read an unsigned integer of 0 through 8 bytes (big-endian). Raises ValueError for an invalid width and BufferError for insufficient bytes or a UTF-8 boundary."""
        ...
    def get_uint_le(self, nbytes: int) -> int:
        """Read an unsigned integer of 0 through 8 bytes (little-endian). Raises ValueError for an invalid width and BufferError for insufficient bytes or a UTF-8 boundary."""
        ...
    def get_int(self, nbytes: int) -> int:
        """Read a signed integer of 0 through 8 bytes (big-endian). Raises ValueError for an invalid width and BufferError for insufficient bytes or a UTF-8 boundary."""
        ...
    def get_int_le(self, nbytes: int) -> int:
        """Read a signed integer of 0 through 8 bytes (little-endian). Raises ValueError for an invalid width and BufferError for insufficient bytes or a UTF-8 boundary."""
        ...
